[package]
description = "Anchor bindings for the AMM native instruction."
edition = "2021"
homepage = "https://raydium.io/"
keywords = ["solana", "raydium", "amm", "anchor"]
name = "amm-anchor"
repository = "https://github.com/raydium-io/raydium-contract-instructions"
version = "0.1.0"

[dependencies]
anchor-lang = "0.26"
raydium-contract-instructions = {path = "../lib"}
solana-program = "1.14.12"
spl-token = {version = "3.3.0", features = ["no-entrypoint"]}
